language: node_js
node_js:
  - "0.12.4"
before_install:
  - npm install -g grunt-cli istanbul
  - npm install coveralls
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
